"""
Pydantic models for Analyst Agent
Defines data shapes for requests and responses
"""

from pydantic import BaseModel, Field
from typing import Literal, Optional, Any

class AnalystRequest(BaseModel):
    """User's question about security logs"""
    query: str = Field(
        ...,
        description="Natural lanaguage questions about firewall logs",
        examples=["How many SQL injection attempts?"]
    )
    csv_path: str = Field(
        default="data/raw/firewall_logs.csv",
        description="Path to the firewall logs CSV file"
    )

class CodeExecutionResult(BaseModel):
    """Result of executing AI-generated code"""
    success: bool = Field(..., description="Whether code executed without errors")
    output: Optional[str] = Field(None, description="Printed output or return value")
    error: Optional[str] = Field(None, description="Error message if execution failed")
    execution_time_ms: float = Field(..., description="How long code took to run")
    code_executed: str = Field(..., description="The actual code that was run")

class AnalystResponse(BaseModel):
    """Final answer from Analyst Agent"""
    query: str = Field(..., description="Original user questions")
    generated_code: str = Field(..., description="Python code generated by AI")
    execution_result: CodeExecutionResult
    natural_language_answer: str = Field(
        ...,
        description="Human-readable answer based on code results"
    )
    confidence: Literal["high", "medium", "low"] = Field(
        ...,
        description="Agent's confidence in the answer"
    )
    data_summary: Optional[dict[str, Any]] = Field(
        None,
        description="key stats from the analysis"
    )
